### ISSUE TITLE
PowerShell Core - File Integrity Test failing

### ISSUE THREAD

**Issue by rdtechie** [PowershellFrameworkCollective/PSModuleDevelopment#104]
In file PSModuleDevelopment/tests/general/FileIntegrity.Tests.ps1 the following code is used to get the encoding:

`[byte[]]$byte = get-content -Encoding byte -ReadCount 4 -TotalCount 4 -Path $Path`

However this will not work in PowerShell Core because the parameter `-Encoding byte` is removed. 

This will work:
`[byte[]]$byte = Get-Content -AsByteStream -ReadCount 4 -TotalCount 4 -Path $Path`

But this is not backwards compatible with PowerShell < 5. So I'm not sure how the PR should looks like for this modification.

**Comment by FriedrichWeinmann** [comment]
Resolved in 2.2.7.90
