### ISSUE TITLE
Write-TemplateItem -Replace operator

### ISSUE THREAD

**Issue by ZanattaMichael** [PowershellFrameworkCollective/PSModuleDevelopment#113]
Within Write-TemplateItem you are using -Replace parameter to perform string replacement of the
placeholders and subsequent string values.

When ingesting large scripts with regex within them (using a scriptblock from a manifest), PowerShell malforms the replacement string, causing the template to be applied twitch within it. If this statement is only performing a string replacement and not requiring regex, can you please adjust to code to use the .Replace method instead?

PS I have encountered this issue with plaster as well.

```
foreach ($param in $Item.ContentParameterScript)
{
    $text = $text -replace "$($identifier)!$([regex]::Escape($param))!$($identifier)", $ParameterScript[$param]
}
```

Proposed Replacement:

```
foreach ($param in $Item.ContentParameterScript)
{
	$text = $text.Replace("$($identifier)!$([regex]::Escape($param))!$($identifier)", $ParameterScript[$param])
}
```

I can confirm that it is working correctly. (I may have made the adjustment to your psm1 locally. :-D :-D)

**Comment by FriedrichWeinmann** [comment]
Sorry for the incredibly late reply.
The notification must have been dropped somewhere and I've been kind of drowned in my current workload.
Will definitely look into fixing this and enhancing the template system in general in the next update phase (which is due after I'm done with the next iteration of PSFramework, where I am approaching my goals). Expect something in this summer's break to happen :)

**Comment by ZanattaMichael** [comment]
Winner!!!!! No worries fred!
