### ISSUE TITLE
Cannot validate argument on parameter 'Language'

### ISSUE THREAD

**Issue by Splaxi** [PowershellFrameworkCollective/PSModuleDevelopment#121]
Freshly created module created like this:

```powershell
Invoke-PSMDTemplate PSFProject -NoFolder
```

Test importing it like this:
```powershell
Import-Module 'C:\Temp\PsDemoScript' -Force
```

Outputs this:
```
Exception calling "InvokeScript" with "4" argument(s): "Cannot validate argument on parameter 'Language'. The term 'New
-Object' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of t
he name, or if a path was included, verify that the path is correct and try again."
At C:\Temp(Not-Synced)\_TestModule_\PsDemoScript\PsDemoScript.psm1:50 char:9
+     else { $ExecutionContext.InvokeCommand.InvokeScript($false, ([scr ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ParameterBindingValidationException
```

![image](https://user-images.githubusercontent.com/8750181/86504797-54f48100-bdbd-11ea-80fc-3292e22514d6.png)

If I remove the following, I can import the module:
```
#internal->scripts->strings.ps1
...
#Import-PSFLocalizedString -Path "$($script:ModuleRoot)\en-us\*.psd1" -Module 'PsDemoScript' -Language 'en-us'
```

**Comment by FriedrichWeinmann** [comment]
Heya, can you give me a few more details of your environment?

+ PowerShell Version
+ PSModuleDevelopment version
+ LanguageMode
+ ExecutionPolicy

The curious thing: The very same line is being run by PSFramework and PSModuleDevelopment, and that does not appear to produce the same issues ...

**Comment by Splaxi** [comment]
Windows 10, fully updated
PowerShell 5.1
EN-US, but with Danish locale numbers and time, including danish keyboard layout
Execution Policy is unrestricted

**Comment by FriedrichWeinmann** [comment]
Heya, I think I found and fixed that issue in PSFramework .1.4.149
Should no longer do the same nastiness.
Can you do a confirm?

**Comment by Splaxi** [comment]
Can you show me the code change? Wanna learn more.

Will test next week.

**Comment by FriedrichWeinmann** [comment]
Sure can, ping me on slack we can do a quick call on that :)
