### ISSUE TITLE
Missing Fallback in build\vsts-build.ps1 for $WorkingDirectory 

### ISSUE THREAD

**Issue by Callidus2000** [PowershellFrameworkCollective/PSModuleDevelopment#137]
https://github.com/PowershellFrameworkCollective/PSModuleDevelopment/blob/ec7623438c6a2113ee367a3f8569cc2b79f3ebcb/build/vsts-build.ps1#L33

If no environment variable is set the build process fails. In the current Template "PSFProject" the following fallback is added:
`if (-not $WorkingDirectory) { $WorkingDirectory = Split-Path $PSScriptRoot }`

**Comment by FriedrichWeinmann** [comment]
Thanks for catching and fixing that in #138 :)
