### ISSUE TITLE
NUPKG Install error "Get-LastResult,Was-Bound"

### ISSUE THREAD

**Issue by Callidus2000** [PowershellFrameworkCollective/PSModuleDevelopment#140]
I'm using the module template, works wonderful with the exception of one of my module-development projects. The use of "vsts-build.ps1" creates a nupgk archive. If I try to install the generated module I receive the error:
```
Install Error: MyModule
The following commands are already available on this system:'Get-LastResult,Was-Bound'. This module 'Dracoon' may override the existing commands. If you still want to install this module 'Dracoon', use -AllowClobber parameter.
```
Get-LastResult,Was-Bound are functions from PSFramework.

Any idea how/where this information is wrongly detected? My module does not contain those functions.

**Comment by FriedrichWeinmann** [comment]
unfortunately, I have no idea where that might happen - never had that happen to me and that should not happen by accident!.
Can you share the code/link to the project?

**Comment by Callidus2000** [comment]
Sharing the real internal module isn't allowed. Therefor I stripped the content and created a dummy module which still creates the corresponding error.
https://github.com/Callidus2000/NuPKGissue140

Reproduce:
```
build\vsts-build.ps1 -Repository "PSMDStaging" -ApiKey x
Install-Module Murks
```

**Comment by FriedrichWeinmann** [comment]
Thanks for sharing that, can definitely reproduce that in almost any permutation imaginable.
Interestingly enough, it works in older versions just fine (tried on 1.0.0.1 that comes preinstalled on windows).
I drilled as far down as I was able to make time for it for now.
I will try to find the culprit involved in this packagemanagement side of things.
Sarcasm might get involved ... ;-)

**Comment by FriedrichWeinmann** [comment]
Ok, had that discussion as promised.
Simply put, we're stuck with this unless we go back to an older version or the v3 starts working correctly.
I don't see that happening anytime soon, alas, sorry :(
