### ISSUE TITLE
Enhancement idea: Invoke-PSMDTemplate returns a string instead of writing into a file

### ISSUE THREAD

**Issue by Callidus2000** [PowershellFrameworkCollective/PSModuleDevelopment#166]
Hi,
just as an idea: What do you think about an option to return the created text directly? This way it could be used for further processing like sending an e-mail without a temporary file.

**Comment by FriedrichWeinmann** [comment]
Fundamentally doable.
Just build a custom object with filename, path and content it would have created instead.
Added to the backlog for the next version (soon(tm))

**Comment by Callidus2000** [comment]
Hi,
did you find some time to look hat the PR? Any hint
- if something should be adjusted to meet the module philosophy or
- if it's completely nonsense (I can take it :wink:)

The auto-check says "All checks have failed", even the pester tests did not show errors. For accessing "Details" I don't have the necessary rights.

**Comment by FriedrichWeinmann** [comment]
Sorry for the late response - been completely buried with work, but I should at least have dropped a note sooner than this. Let me take a look ...

**Comment by FriedrichWeinmann** [comment]
Alright: merged, extended and released :)
Thanks again for the contribution
