### ISSUE TITLE
Bug in version 2.2.11.138 breaks template system

### ISSUE THREAD

**Issue by trondr** [PowershellFrameworkCollective/PSModuleDevelopment#172]
In version 2.2.11.138 issue:

WARNING: [11:57:41][Invoke-PSMDTemplate] Failed to: Creating file/project from template TEPSAdvancedFunction 1.0.0.0 |
Cannot bind parameter because parameter 'FunctionName' is specified more than once. To provide multiple values to
parameters that can accept multiple values, use the array syntax. For example, "-parameter value1,value2,value3".

Believed to be caused by the following code:
PSModuleDevelopment/functions/templating/Invoke-PSMDTemplate.ps1

Line 413 and 415. -FunctionName parameter  is used twice

![2022-04-29_11-51-34](https://user-images.githubusercontent.com/2294892/165923266-9c77d4d0-07cd-4c53-98a0-2b7b5c496d70.png)

Workaround: Rollback to version: 2.2.10.134

**Comment by FriedrichWeinmann** [comment]
Heya @trondr ,
thanks for catching that bug!
That one slipped through due to the last minute changes only having been tested against 7+, and the splatting / Explicitly bound conflicts were eliminated there.
2.2.11.139 is not on the gallery and should fix that
