### ISSUE TITLE
Templates Tests: Extend forbidden commands

### ISSUE THREAD

**Issue by FriedrichWeinmann** [PowershellFrameworkCollective/PSModuleDevelopment#186]
Should disallow:

+ Clear-Host
+ Get-Variable
+ Set-Variable
+ Clear-Variable
+ Remove-Variable
+ New-Variable

**Comment by AndiBellstedt** [comment]
Out of curiosity, why to disable the variable commands?

For clear-host, I agree with you in the absolute most cases. That should be a user decision and not a developer one.

**Comment by FriedrichWeinmann** [comment]
The variable commands solve problems that usually can be avoided by healthier design practices.
There may be situations where it's valid to use them, but they are rare and the new defaults can be overridden, so explicitly allowing intended usage is still possible.

They generally make code refactoring harder (bulk renaming a variable tends to fail on those for example).

Examples of things I've seen them used for but (strongly) disagree with:

+ Declaring constants: Meaningless in PowerShell - they die anyway the moment the current context dies. The entire reason they exist in C# does not apply to PowerShell (Named compile-time static values are not needed in a language that does not compile).
+ Writing to & reading from parent scopes: Parameters and Output are pretty awesome things. Also doesn't translate well across module boundaries.
+ Dynamic variable creation: Hashtables are awesome and should be used instead

**Comment by FriedrichWeinmann** [comment]
Implemented in v2.2.11.163
