### ISSUE TITLE
Invoke-PSMDTemplate should have author parameter

### ISSUE THREAD

**Issue by autosysops** [PowershellFrameworkCollective/PSModuleDevelopment#190]
Now the author is auto filled by the env variable which can be frustrating as in my experience you often want something a bit different. I think there should at least be an option parameter which can be passed on to the invoke function in the template to use so it's set right the first time.

**Comment by FriedrichWeinmann** [comment]
Heya,

you can define default parameter values using the configuration system.
E.g.:

```powershell
# Set setting for this console
Set-PSFConfig -FullName PSModuleDevelopment.Template.ParameterDefault.Author -Value 'Max Mustermann'

# Make it remember it across sessions
Register-PSFConfig -FullName PSModuleDevelopment.Template.ParameterDefault.Author
```

The same is true for any other parameter you so choose to use :)

**Comment by FriedrichWeinmann** [comment]
Heya,
given that there's not been any further response on this, I'm going to close this issue now.
Thanks for bringing this up - the help on the command is really insufficient on this and the next release that will be shipped soon will have another example on how to do this:

```powershell
Invoke-PSMDTemplate MiniModule -Parameters @{ Author = 'Fred' }
```
