### ISSUE TITLE
New common parameter 'ProgressAction' missing in Common Parameter array of pester test "Help.Tests.ps1"

### ISSUE THREAD

**Issue by jklotzsche-msft** [PowershellFrameworkCollective/PSModuleDevelopment#192]
Line 97 of Help.Tests.ps1 lists all common parameters. The new 'ProgressAction' common parameter is missing here. This results in multiple errors when running the pester.ps1 script, because parameter help is missing.

Current line 97 in Help.Tests.ps1:
`$common = 'Debug', 'ErrorAction', 'ErrorVariable', 'InformationAction', 'InformationVariable', 'OutBuffer', 'OutVariable', 'PipelineVariable', 'Verbose', 'WarningAction', 'WarningVariable'`

Should be:
`$common = 'Debug', 'ErrorAction', 'ErrorVariable', 'InformationAction', 'InformationVariable', 'OutBuffer', 'OutVariable', 'PipelineVariable', 'Verbose', 'WarningAction', 'WarningVariable', 'ProgressAction'`

My tests were successful by simply adding the parameter to the common parameters array.

**Comment by FriedrichWeinmann** [comment]
Implemented in v2.2.11.163
