### ISSUE TITLE
Bug in build.ps1 for template "AzureFunction"

### ISSUE THREAD

**Issue by jklotzsche-msft** [PowershellFrameworkCollective/PSModuleDevelopment#196]
**Isssue**
When executing the build.ps1 script, the files "run.ps1" and "function.json" for each function are empty.
Tested using PowerShell 7.4.2

**Reason**
Line 31 + 32:

```PowerShell
$httpCode = Get-Content -Path "$PSScriptRoot\functionHttp\run.ps1" | Join-String "`n"

$httpConfig = Get-Content -Path "$PSScriptRoot\functionHttp\function.json" | Join-String "`n"
```

By using Join-String with positional parameter, the parameter "Property" is used.

**Solution**
Correct would be "Seperator".
Therefore, when you add the parameter name it works:

```PowerShell
$httpCode = Get-Content -Path "$PSScriptRoot\functionHttp\run.ps1" | Join-String -Separator "`n"

$httpConfig = Get-Content -Path "$PSScriptRoot\functionHttp\function.json" | Join-String -Separator "`n"
```

Please add the parameter name :-) Thank you!

**Comment by FriedrichWeinmann** [comment]
Thart _only_ happens when you use the _inferior_ version of Join-String.
Had you used the proper one, that would have been a non-issue :D

:cough:

Ehm, yes, fixing that, nothing to see here ... ^^
