### ISSUE TITLE
function template doesn't bring over name.

### ISSUE THREAD

**Issue by AndrewPla** [PowershellFrameworkCollective/PSModuleDevelopment#38]
Using Version 2.2.4.18 
`Get-PSMDtemplate function | invoke-psmdtemplate -name 'Example-Command'` creates the Example-Command.ps1 file but the name isn't applied and 'þnameþ' is there instead of 'Example-Command'

**Comment by FriedrichWeinmann** [comment]
Should be resolved in the current release
