### ISSUE TITLE
-UserMode in template file isn't correct

### ISSUE THREAD

**Issue by Splaxi** [PowershellFrameworkCollective/PSModuleDevelopment#55]
https://github.com/PowershellFrameworkCollective/PSModuleDevelopment/blob/fb71f1ceae214d155ef19d8704d5d4d4c72ea348/templates/PSFProject/install.ps1#L2381

It looks like your "[switch] $UserMode" in your template file is wrong.

If you look at the install.ps1 for the module it self, it looks like you did enhance that to do the correct logic:

https://github.com/PowershellFrameworkCollective/PSModuleDevelopment/blob/4b3bc16471e1f575d320e899585f74ded70c22fb/install.ps1#L55

I would expect that several of your other modules might have the same issue. I found it at least in the PSFramework.

**Comment by FriedrichWeinmann** [comment]
Working as designed in the template, so I'm closing this.
Thank you for fixing this in the PSFramework 👍
