### ISSUE TITLE
Show-PSMDSyntax

### ISSUE THREAD

**Issue by Splaxi** [PowershellFrameworkCollective/PSModuleDevelopment#68]
Cmdlet / Function to assist with parametersets and mandatory parameters.

```
Show-PSMDSyntax -CommandText 'Import-D365Bacpac -ImportModeTier2 -SqlUser "sqladmin" -SqlPwd "XyzXyz" -BacpacFile "C:\temp\uat.bacpac"' -Mode "Validate"'
```
Will validate all the parametersets and their parameters, against the supplied CommandText. Mandatory parameters will be marked with green asterisk if found, while mandatory parameters that are not found will be marked with magenta asterisk.

```
Show-PSMDSyntax -CommandText 'Import-D365Bacpac ' -Mode "ShowParameters"
```
Will traverse all parameter sets and show their parameters with mandatory being color marked

`-IncludeHelp`
This switch will output the color help guide for the user to see an explanation

**Comment by FriedrichWeinmann** [comment]
has been been implemented by @Splaxi and released in one of the recent releases.
Thanks again for this useful command! 👍
